name: test
on: [ push, pull_request ]
env:
  CI: true
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }} x ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 18, 20, 22 ]
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Build webextension (Chrome)
        run: |
          pwd
          pwd | sed -e 's:\\:/:g'
          echo file://$(pwd | sed -e 's:\\:/:g')/webextension-toolbox.config.js
          npm run dist chrome
        working-directory: packages/webextension
      - name: Test
        run: yarn test
