name: test
on: [ push, pull_request ]
env:
  CI: true
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }} x ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 14 ]
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 75abe354d1e1d26708bc222ca781467939d3c2ce
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - run: yarn run build
      - run: npm run dev chrome
        working-directory: packages/webextension/
